env:
  node: true
  es6: true
extends:
  - eslint-config-prettier
  - eslint:recommended

plugins:
  - prettier

globals:
  Promise: true

rules:
  prettier/prettier:
    - error
  arrow-body-style: off
  no-console: off


parser: babel-eslint

parserOptions:
  sourceType: module
