name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
        USERNAME: ${{ secrets.test_username }}
        PASSWORD: ${{ secrets.test_password }}
        API_KEY_ID: ${{ secrets.test_api_key }}
        API_KEY_SECRET: ${{ secrets.test_api_key_secret }}
